epc <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.string = "?");
epc$DateTime <- paste(epc$Date, epc$Time);
epc$Date2 <- paste(epc$Date, epc$Time);
epc$Date2 <- as.Date(epc$Date2, format = "%d/%m/%Y %H:%M:%S");
library(dplyr);
epcFileSubset <- filter(epc, Date2 >= as.Date("2007-02-01 00:00:00"), Date2 < as.Date("2007-02-03 00:00:00"));
library(datasets);
png(filename="plot3.png");
with(epcFileSubset, plot(as.POSIXct(strptime(DateTime, "%d/%m/%Y %H:%M:%S")), Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"));
with(epcFileSubset, lines(as.POSIXct(strptime(DateTime, "%d/%m/%Y %H:%M:%S")), Sub_metering_2, col = "red"));
with(epcFileSubset, lines(as.POSIXct(strptime(DateTime, "%d/%m/%Y %H:%M:%S")), Sub_metering_3, col = "blue"));
legend("topright", lty = 1, col = c("black", "red","blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"));
dev.off();